# Generated by Django 3.1.1 on 2020-09-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='Test', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(default='Test', max_length=10),
        ),
    ]
