# Generated by Django 3.1.1 on 2020-10-22 10:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='tracked_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='ScrapeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='-', max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('page', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('keyword', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RankingTool.keyword')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RankingTool.product')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordCrawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('keyword', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RankingTool.keyword')),
                ('marketplace', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='RankingTool.marketplace')),
                ('products', models.ManyToManyField(to='RankingTool.ScrapeProduct')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='keyword',
            field=models.ManyToManyField(to='RankingTool.Keyword'),
        ),
    ]
