# Generated by Django 3.1.1 on 2020-09-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0002_auto_20200925_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='Test', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(default='Test', max_length=200),
        ),
    ]
