# Generated by Django 3.1.1 on 2020-10-27 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0002_auto_20201027_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='marketplace',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RankingTool.marketplace'),
        ),
    ]
