# Generated by Django 3.1.1 on 2020-10-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0002_auto_20201022_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordcrawl',
            name='marketplace',
        ),
    ]
