# Generated by Django 3.1.1 on 2020-10-22 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0003_remove_keywordcrawl_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordcrawl',
            name='marketplace',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='RankingTool.marketplace'),
        ),
    ]
