# Generated by Django 3.1.1 on 2020-10-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0003_keyword_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
