# Generated by Django 3.1.1 on 2020-09-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0003_auto_20200928_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='keyword',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='page',
        ),
        migrations.RemoveField(
            model_name='product',
            name='position',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
