# Generated by Django 3.1.1 on 2020-09-29 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0004_auto_20200929_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='Test', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RankingTool.keyword'),
        ),
    ]
