# Generated by Django 3.1.1 on 2020-10-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0005_auto_20201027_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('asin', 'sku')},
        ),
    ]
