# Generated by Django 3.1.1 on 2020-10-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0006_auto_20201027_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(default='', max_length=10),
        ),
    ]
