# Generated by Django 3.1.1 on 2020-09-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0007_auto_20200929_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='keyword',
            field=models.CharField(default='Test', max_length=200),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
