# Generated by Django 3.1.1 on 2020-10-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0008_auto_20201027_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('keyword', 'marketplace')},
        ),
    ]
