# Generated by Django 3.1.1 on 2020-10-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0008_auto_20200929_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='Test', max_length=200)),
            ],
        ),
    ]
