# Generated by Django 3.1.1 on 2020-10-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0009_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(default='Test', max_length=10)),
                ('sku', models.CharField(default='Test', max_length=200)),
                ('keyword', models.CharField(default='Test', max_length=200)),
                ('image_url', models.CharField(default='Test', max_length=200)),
                ('title', models.CharField(default='Test', max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
    ]
