# Generated by Django 3.1.1 on 2020-10-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0010_scrapeproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapeproduct',
            old_name='rank',
            new_name='page',
        ),
        migrations.AddField(
            model_name='scrapeproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='scrapeproduct',
            name='rating',
            field=models.CharField(default='Test', max_length=200),
        ),
    ]
