# Generated by Django 3.1.1 on 2020-10-06 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0011_auto_20201006_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeproduct',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
