# Generated by Django 3.1.1 on 2020-10-06 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0013_auto_20201006_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeproduct',
            name='sku',
        ),
        migrations.AlterField(
            model_name='scrapeproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 13, 54, 31, 908778)),
        ),
    ]
