# Generated by Django 3.1.1 on 2020-10-06 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0014_auto_20201006_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 14, 46, 53, 397768)),
        ),
    ]
