# Generated by Django 3.1.1 on 2020-10-06 14:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0015_auto_20201006_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeproduct',
            name='asin',
        ),
        migrations.RemoveField(
            model_name='scrapeproduct',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='scrapeproduct',
            name='keyword',
        ),
        migrations.AddField(
            model_name='scrapeproduct',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RankingTool.product'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='keyword',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RankingTool.keyword'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapeproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 16, 41, 10, 122723)),
        ),
        migrations.AlterField(
            model_name='scrapeproduct',
            name='rating',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapeproduct',
            name='title',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
