# Generated by Django 3.1.1 on 2020-10-06 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0017_auto_20201006_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 17, 22, 24, 913339)),
        ),
    ]
