# Generated by Django 3.1.1 on 2020-10-07 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0018_auto_20201006_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tracked_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scrapeproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 12, 32, 21, 315635)),
        ),
    ]
