# Generated by Django 3.1.1 on 2020-10-07 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0021_auto_20201007_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 45, 40, 163967)),
        ),
        migrations.AlterField(
            model_name='scrapeproduct',
            name='rating',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
