# Generated by Django 3.1.1 on 2020-10-07 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0026_auto_20201007_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='keyword',
        ),
        migrations.AddField(
            model_name='product',
            name='keyword',
            field=models.ManyToManyField(to='RankingTool.Keyword'),
        ),
        migrations.AlterField(
            model_name='scrapeproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 19, 35, 24, 714415)),
        ),
    ]
