# Generated by Django 3.1.1 on 2020-10-07 18:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0027_auto_20201007_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeproduct',
            name='keyword',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RankingTool.keyword'),
        ),
        migrations.AlterField(
            model_name='scrapeproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 20, 35, 47, 269852)),
        ),
    ]
