# Generated by Django 3.1.1 on 2020-10-07 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0028_auto_20201007_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeproduct',
            name='keyword',
        ),
        migrations.AlterField(
            model_name='scrapeproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 20, 41, 15, 2054)),
        ),
    ]
