# Generated by Django 3.1.1 on 2020-10-07 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0030_auto_20201007_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 21, 22, 18, 997670)),
        ),
    ]
