# Generated by Django 3.1.1 on 2020-10-08 18:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0036_auto_20201008_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 20, 12, 29, 499899)),
        ),
        migrations.CreateModel(
            name='KeywordCrawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 10, 8, 20, 12, 29, 499899))),
                ('keyword', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RankingTool.keyword')),
                ('products', models.ManyToManyField(to='RankingTool.ScrapeProduct')),
            ],
        ),
    ]
