# Generated by Django 3.1.1 on 2020-10-08 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0037_auto_20201008_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcrawl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 20, 13, 46, 986119)),
        ),
        migrations.AlterField(
            model_name='scrapeproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 20, 13, 46, 985119)),
        ),
    ]
