# Generated by Django 3.1.1 on 2020-10-22 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RankingTool', '0047_auto_20201019_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcrawl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 9, 42, 27, 141804)),
        ),
        migrations.AlterField(
            model_name='scrapeproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 9, 42, 27, 141804)),
        ),
    ]
